jobs:    
  - name: my-ci-test_runCI
    type: runCI
    steps:
      - IN: my-ci-test_ciRepo
      - IN: sample_kv_int
      - IN: sample_aws_int
    flags:
      - production 
     

  - name: shipctl-checking
    type: runSh
    runtime:
      container: false
    steps:
      - IN: sample_kv_int
      - IN: sample_aws_int
      - TASK:
          name: unpatched
          script:
            - shipctl get_integration_resource_field sample_kv_int key1
            # - shipctl get_integration_resource_field sample_kv_int invalid_key
            - shipctl get_integration_resource_field sample_aws_int accessKey
            # - shipctl get_integration_resource_field sample_aws_int invalid_key
            - shipctl get_integration_resource_field invalid_resource_name accessKey
            
  - name: shipctl-container-checking
    type: runSh
    steps:
      - IN: sample_kv_int
      - IN: sample_aws_int
      - TASK:
          name: container-test
          runtime:
            options:
              imageName: "drydock/u16"
              imageTag: "master"
          script:
            - shipctl get_integration_resource_field sample_kv_int key1
            # - shipctl get_integration_resource_field sample_kv_int invalid_key
            - shipctl get_integration_resource_field sample_aws_int accessKey
            # - shipctl get_integration_resource_field sample_aws_int invalid_key
            - shipctl get_integration_resource_field invalid_resource_name accessKey

  - name: irc-shipctl-testing
    type: runSh
    steps:
      - IN: irc-notifier
      - TASK:
          name: should-message-irc
          script:
            - echo "hello"
            - shipctl notify irc-notifier --text="hello from runsh jobin RC"
            
  - name: irc-notify-testing
    type: runSh
    on_success:
      NOTIFY:
        - name: freenode-notifier
        - name: ircnet-notifier
    steps:
      - TASK:
          name: should-message-irc
          script:
            - echo "hello"

  - name: airbrake-windows
    type: runSh
    runtime:
      nodePool: custom-windows-server
    steps:
      - IN: airbrake-userlevel-notifier
      - TASK:
          name: should-message-airbrake
          script:
            - echo "hello"
            - echo $env:TEMP
            - git clone https://github.com/scriptnull/node.git $env:TEMP\xnode
            - cd $env:TEMP\xnode\shipctl\x86_64\WindowsServer_2016
            - ./install.ps1 
            - shipctl notify airbrake-userlevel-notifier --project-id="215168" --type="deploy"  --environment="wprod" --username="w16user" --repository="https://github.com/vishnu-shippable/local-test-cd" --revision="w.u.p.$BUILD_NUMBER" --version="v4" --email="vishnu@shippable.com"

  - name: airbrake-userlevel-testing
    type: runSh
    steps:
      - IN: airbrake-userlevel-notifier
      - TASK:
          name: should-message-airbrake
          script:
            - shipctl notify airbrake-userlevel-notifier --project-id="215168" --type="deploy"  --environment="production" --username="tron" --repository="https://github.com/vishnu-shippable/local-test-cd" --revision="user.prod.$BUILD_NUMBER" --version="v4" --email="vishnu@shippable.com"
            
  - name: airbrake-projectlevel-testing
    type: runSh
    steps:
      - IN: airbrake-projectlevel-noifier
      - TASK:
          name: should-message-airbrake
          script:
            - shipctl notify airbrake-projectlevel-noifier --type="deploy"  --environment="production" --username="pro" --repository="https://github.com/vishnu-shippable/local-test-cd" --revision="proj.prod.$BUILD_NUMBER" --version="v4" --email="vishnu@shippable.com"
            
resources:
  - name: freenode-notifier
    type: notification
    versionTemplate:
      method: irc
      recipients:
        - "chat.freenode.net#shiptest"

  - name: ircnet-notifier
    type: notification
    versionTemplate:
      method: irc
      recipients:
        - "open.ircnet.net#shiptest"

  - name: sample_kv_int
    type: integration
    integration: sample_kv
    
  - name: sample_aws_int
    type: integration
    integration: sample_aws
    
  - name: airbrake-userlevel-notifier
    type: notification
    integration: sample_rc_airbrake_sub_int

  - name: airbrake-projectlevel-noifier
    type: notification
    integration: sample_rc_airbrake_sub_int
    versionTemplate:
      recipients:
        - 215168    # only the first project ID will be considered by shipctl notify
