jobs:
  - name: old-x86-64-ubuntu-16-04-container-artifactory-cli
    type: runSh
    steps:
      - IN: test-artifactory-cli
      - TASK:
        - script: echo "build number is $BUILD_NUMBER" > myfile.old.$BUILD_NUMBER.txt
        - script: jfrog rt u myfile.old.$BUILD_NUMBER.txt generic-local/myfile.old.$BUILD_NUMBER.txt


  - name: old-x86-64-ubuntu-16-04-container-envs-all-in
    type: runSh
    steps:
      - IN: master-cluster
      - IN: master-dockerOptions
      - IN: master-file
      - IN: master-gitRepo
      - IN: master-image
      - IN: checking-do-integration
      - IN: checking-ssh-integration
      - IN: master-params
      - IN: master-replicas
      - IN: master-trigger
      - IN: master-version
      - TASK:
        - script: printenv
        
  - name: runsh-min
    type: runSh
    runtime:
      container: false
    steps:
      - TASK:
          name: single-cmd-should-work
          script:
            - dir
            

  - name: windows-runsh-container-min
    type: runSh
    runtime:
      container: true
    steps:
      - TASK:
          name: say-hello-world
          runtime:
            options:
              imageName: "drydock/w16"
              imageTag: "master"
          script:
            - Write-Output "Hello world"
            - docker ps | Measure-Object -line |  %{ $_.Lines }
            - docker ps -a | Measure-Object -line |  %{ $_.Lines }
