jobs:    
  - name: my-ci-test_runCI
    type: runCI
    steps:
      - IN: my-ci-test_ciRepo
      - IN: sample_kv_int
      - IN: sample_aws_int
    flags:
      - production 
     

  - name: shipctl-checking
    type: runSh
    runtime:
      container: false
    steps:
      - IN: sample_kv_int
      - IN: sample_aws_int
      - TASK:
          name: unpatched
          script:
            - shipctl get_integration_resource_field sample_kv_int key1
            # - shipctl get_integration_resource_field sample_kv_int invalid_key
            - shipctl get_integration_resource_field sample_aws_int accessKey
            # - shipctl get_integration_resource_field sample_aws_int invalid_key
            - shipctl get_integration_resource_field invalid_resource_name accessKey
            
  - name: shipctl-container-checking
    type: runSh
    steps:
      - IN: sample_kv_int
      - IN: sample_aws_int
      - TASK:
          name: container-test
          runtime:
            options:
              imageName: "drydock/u16"
              imageTag: "master"
          script:
            - shipctl get_integration_resource_field sample_kv_int key1
            # - shipctl get_integration_resource_field sample_kv_int invalid_key
            - shipctl get_integration_resource_field sample_aws_int accessKey
            # - shipctl get_integration_resource_field sample_aws_int invalid_key
            - shipctl get_integration_resource_field invalid_resource_name accessKey
            
  - name: irc-testing
    type: runSh
    runtime:
      container: false
    steps:
      - IN: irc-notifier
      - TASK:
          name: should-message-irc
          script:
            - echo "hello"
            - shipctl notify irc-notifier --text="hello from runsh job"
            - echo "bye"

resources:
  - name: irc-notifier
    type: notification
    versionTemplate:
      method: irc
      recipients:
        - "herbert.freenode.net##ship-test"

  - name: sample_kv_int
    type: integration
    integration: sample_kv
    
  - name: sample_aws_int
    type: integration
    integration: sample_aws
    
